# Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe

# This program is free software: you can redistribute it and/or modify
# #it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme

configMapGenerator:
  - name: rezept-env
    literals:
      - TZ=Europe/Berlin

commonLabels:
  app.kubernetes.io/component: appserver
  app.kubernetes.io/framework: node
  app.kubernetes.io/managed-by: kustomize

# Reihenfolge fuer die Installation der Kubernetes Ressourcen
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
